version: "3.8"

services:
  rag-app:
    build: .
    ports:
      - "${PORT}:7860"
    env_file:
      - .env
    volumes:
      - ./adresowo_descriptions:/app/${OUTPUT_FOLDER}
    command: ./start.sh